### ISSUE TITLE
Training data resolution and dataset availability

### ISSUE THREAD

**Issue by rawanametalinefam** [Ayushkumawat/Advanced-Aerial-Drone-Detection-System#1]
I understand this repo is one year old with no updates. However, I need some information about the dataset that the model was trained on. The following dataset was not published, so I'm unable to proceed without it. What is the optimal resolution for the model to work with?

**Comment by Ayushkumawat** [comment]
The dataset can be downloaded from here - https://universe.roboflow.com/drone-detection-ehdcs/drone-dataset-by-ayushkumawat, let me know you require any additional help.

**Comment by KnowHowZone** [comment]
Hey @Ayushkumawat could you please tell me which python version exactly if possible you coded this code as i am trying to run it on my win 11 laptop in python version 3.8 with all requirements installed , code is showing error that "PS D:\Advanced-Aerial-Drone-Detection-System-main\Advanced-Aerial-Drone-Detection-System-main> & C:/Users/rajak/AppData/Local/Programs/Python/Python38/python.exe d:/Advanced-Aerial-Drone-Detection-System-main/Advanced-Aerial-Drone-Detection-System-main/experiment.py
Traceback (most recent call last):
  File "d:/Advanced-Aerial-Drone-Detection-System-main/Advanced-Aerial-Drone-Detection-System-main/experiment.py", line 1, in <module>
    import cv2
  File "C:\Users\rajak\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\rajak\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "C:\Users\rajak\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "C:\Users\rajak\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\rajak\AppData\Local\Programs\Python\Python38\lib\site-packages\cv2\gapi\__init__.py", line 323, in <module>
    cv.gapi.wip.GStreamerPipeline = cv.gapi_wip_gst_GStreamerPipeline
AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)       
PS D:\Advanced-Aerial-Drone-Detection-System-main\Advanced-Aerial-Drone-Detection-System-main> " and i am not getting what is creating circular loop import situation here , please help me if not possible just give me some piece of advice.

**Comment by Ayushkumawat** [comment]
Thank you for raising the issue! From the error logs you shared, it seems like the problem may be related to the OpenCV version installed on your system, could you confirm the exact OpenCV version you have installed? I recommend trying to downgrade OpenCV as newer versions might introduce breaking changes.

Also, I noticed you added a comment in another issue. To help keep things organized, could you please create a new issue for your problem? This will allow me to track your issue separately as I close the current one.
